# Generated by Django 5.2.14 on 2026-06-11 18:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankMovement',
            fields=[
                ('bank_movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('glosa', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto en CLP', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('collection_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contract_id', models.PositiveIntegerField()),
                ('mes_cobro', models.DateField()),
                ('monto_cobro', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(choices=[('CLP', 'CLP'), ('UF', 'UF')], max_length=3)),
            ],
            options={
                'ordering': ['mes_cobro', 'contract_id'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_clp', models.DecimalField(decimal_places=2, help_text='Monto aplicado desde el movimiento bancario en CLP', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.bankmovement')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.collection')),
            ],
            options={
                'unique_together': {('collection', 'bank_movement')},
            },
        ),
        migrations.AddField(
            model_name='bankmovement',
            name='collections',
            field=models.ManyToManyField(related_name='bank_movements', through='tasks.CollectionPayment', to='tasks.collection'),
        ),
    ]
